# Generated by Django 3.0.6 on 2020-06-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Client Name')),
                ('age', models.IntegerField(null=True, verbose_name='Client Age')),
                ('hospital_bill', models.FloatField(null=True, verbose_name='Hospital Bill')),
                ('prediction', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Case Value')),
                ('last_completed_form_page', models.IntegerField(default=0, verbose_name='Last Completed Form Field')),
            ],
        ),
    ]
