# Generated by Django 3.0.6 on 2020-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_claudius', '0002_auto_20200602_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='last_completed_form_page',
            field=models.IntegerField(default=0, verbose_name='Last Completed Form Field'),
        ),
    ]
