# Generated by Django 3.0.6 on 2020-06-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_claudius', '0003_case_last_completed_form_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='last_completed_form_page',
        ),
    ]
